# Generated by Django 4.1.3 on 2022-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='eventplanner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eventPlanner/'),
        ),
    ]
